#version: "3.9"

services:
  catalog-db:
    image: postgres:17
    container_name: catalog-db
    restart: always
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: e-mall
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - catalog_data:/var/lib/postgresql/data
    networks:
      - catalog
  catalog-app:
    build: .
    container_name: catalog-app
    depends_on:
      - catalog-db
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://catalog-db:5432/catalog 
      SPRING_DATASOURCE_USERNAME: e-mall
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PORT: 8080
      SPRING_PROFILES_ACTIVE: prod

      ##-------- Services Urls ---------
      CAMPAIGNS_IP_ADDRESS: campaigns-app
      CAMPAIGNS_PORT: 8080
      ACCOUNTS_IP_ADDRESS: accounts-app
      ACCOUNTS_PORT: 8080
      ORDER_HUB_IP_ADDRESS: order-hub-app
      ORDER_HUB_PORT: 8080
      MEDIA_MANAGER_IP_ADDRESS: media-manager-app
      MEDIA_MANAGER_PORT: 8080
      OPENAI_MODERATION_API_KEY: ${OPENAI_MODERATION_API_KEY}
    networks:
      - services
      - catalog

  catalog-tests:
    build:
      context: .
      target: build
    working_dir: /src
    depends_on:
      - catalog-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://catalog-db:5432/catalog
      SPRING_DATASOURCE_USERNAME: e-mall
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      OPENAI_MODERATION_API_KEY: ${OPENAI_MODERATION_API_KEY}

    entrypoint: [ "mvn" ]
    command: [ "-B", "test" ]
    networks:
      - catalog
      - edge

volumes:
  catalog_data:

networks:
  services:
    driver: bridge
    internal: true
    name: services

  catalog:
    driver: bridge
    internal: true
    name: catalog-db
  edge:
    driver: bridge